name: Ubuntu 22.04

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build-ubuntu22:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y qtbase5-dev qttools5-dev qttools5-dev-tools libqt5charts5-dev libboost-all-dev
      - name: Clone ultranote-core
        run: |
          rm -rf cryptonote
          git clone https://github.com/xun-project/ultranotei-core.git cryptonote
      - name: Build
        id: build
        run: |
          xuni_ver=$(echo "$GITHUB_REF" | sed 's|refs/tags/||')
          release_name=xuni-cli-desktop-ubuntu-2204-v"$xuni_ver"
          build_folder="build/release"
          make -j4 build-release
          mkdir $release_name
          mkdir -p $release_name/icon
          mv $build_folder/ultranote-desktop $release_name
          cp ultranote-desktop.desktop $release_name
          cp src/images/UltraNoteLogo.png $release_name/icon
          tar -czf "$release_name".tar.gz "$release_name"
          sha256=$(shasum -a 256 "$release_name".tar.gz | awk '{print toupper($1)}')
          echo "sha256=${sha256}" >> $GITHUB_OUTPUT
          echo "release_name=${release_name}.tar.gz" >> $GITHUB_OUTPUT
          echo "xuni_ver=${xuni_ver}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: ${{ steps.build.outputs.release_name }}
          name: UltraNote Desktop v${{ steps.build.outputs.xuni_ver }}
          body: |
            [Download for Ubuntu 22.04](../../releases/download/${{ steps.build.outputs.ccx_version }}/${{ steps.build.outputs.release_name }}) **${{ steps.build.outputs.release_name }}**
            `SHA256 : ${{ steps.build.outputs.sha256 }}`
          append_body: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}